delete from Taco_Order_Tacos;
delete from Taco_Ingredients;
delete from Taco;
delete from Taco_Order;
delete from Ingredient;
insert into Ingredient (id, name, type) values ('FLTO', 'Flour Tortilla', 'WRAP');
insert into Ingredient (id, name, type) values ('COTO', 'Corn Tortilla', 'WRAP');
insert into Ingredient (id, name, type) values ('GRBF', 'Ground Beef', 'PROTEIN');
insert into Ingredient (id, name, type) values ('CARN', 'Carnitas', 'PROTEIN');
insert into Ingredient (id, name, type) values ('TMTO', 'Diced Tomatoes', 'VEGGIES');
insert into Ingredient (id, name, type) values ('LETC', 'Lettuce', 'VEGGIES');
insert into Ingredient (id, name, type) values ('CHED', 'Cheddar', 'CHEESE');
insert into Ingredient (id, name, type) values ('JACK', 'Monterrey Jack', 'CHEESE');
insert into Ingredient (id, name, type) values ('SLSA', 'Salsa', 'SAUCE');
insert into Ingredient (id, name, type) values ('SRCR', 'Sour Cream', 'SAUCE');
-- insert into Taco_Order (ID, DELIVERY_NAME, DELIVERY_STREET, DELIVERY_CITY, DELIVERY_STATE, DELIVERY_ZIP, CC_NUMBER, CC_EXPIRATION, CCCVV, PLACED_AT) values(1, 'Petros Prokopiou', 'Mikras asias 3', 'Seattle', 'AT', '15233','4038633121661637', '12/24', '123', CURRENT_TIMESTAMP);
-- insert into Taco (ID, NAME, CREATED_AT) values (1, 'Super Taco', CURRENT_TIMESTAMP);